theme: jekyll-theme-cayman
title: mind-models
description: An open library and schema for psychological models, cognitive frameworks, emotional dynamics, and behavioral patterns.
url: https://arigitshub.github.io
baseurl: /mind-models
show_downloads: false
